### ISSUE TITLE
Ruby 2.4 can't install OpenSSL 1.0.2u, GPG key can't be retrieved

### ISSUE THREAD

**Issue by MSP-Greg** [MSP-Greg/setup-ruby-pkgs#16]
Due to issues with GPG servers, the signing key for the OpenSSL 1.0.2u package can't be retrieved.  The package is retrieved from GitHub.

Disabled the GPG verification for only the 1.0.2u package in commit d3ed56f765.

Fixed in release 1.29.0.

ping @rhenium

**Comment by rhenium** [comment]
Thanks 👍 

The latest GitHub Actions on ruby/openssl ran fine. https://github.com/ruby/openssl/pull/399/checks?check_run_id=2886232526
