### ISSUE TITLE
Puma's CI fails on Ubuntu

### ISSUE THREAD

**Issue by eregon** [MSP-Greg/setup-ruby-pkgs#2]
https://github.com/puma/puma/runs/556273752

On Ubuntu/with `apt-get`, one always needs `apt-get update` first, otherwise `apt-get install <package>` might not find it, or refer to an old URL which is no longer available.
I think that should be fixed in this action, to always `apt-get update` before `apt-get install`.

**Comment by MSP-Greg** [comment]
I'll fix it, but the problem in Puma is with http://azure.archive.ubuntu.com/ubuntu bionic/universe
  Could not connect to azure.archive.ubuntu.com:80 (52.177.174.250), connection timed out

I've seen it happen with just one job of many in CI.

**Comment by MSP-Greg** [comment]
Done via https://github.com/MSP-Greg/setup-ruby-pkgs/commit/ccb34b9f966fc176ab20fcc9e906d96adeb303c3 and v1.1.0.

**Comment by eregon** [comment]
Thanks!

FWIW Docker images also need this, so that's why I know about it.

**Comment by eregon** [comment]
FWIW, I today found https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners (in the context of https://github.com/ruby/yarp/issues/1476)
